### ISSUE TITLE
Can I get the part of prediction in the image

### ISSUE THREAD

**Issue by sjwhhhi** [Rostifar/NYUDepthNet#1]
Thank for your code.
It is amazing about NYU dataset.
However, can I only get the part prediction like "floor"?

**Comment by rbriden** [comment]
Hello @sjwhhhi, are you asking about the semantic label portion of the neural network? Currently, my repository is only setup up to output depth data since I created this repository to supplement my depth estimation research. However, if you do need the semantic label outputs I could probably write an implementation within the next two weeks. Does that help?

- Ross Briden

**Comment by sjwhhhi** [comment]
@Rostifar 
Yes , I want to get the label outputs.
It will be helpful! 
If it is finished, please put on the GitHub!
Thank you very much!
