### ISSUE TITLE
Can not find main.py

### ISSUE THREAD

**Issue by jiao0805** [Rostifar/NYUDepthNet#3]
Hi,

I want to use your code to predict my own data.
It seems that there is only network structure in this code.
Is it a unfinished version now?
And where is the main.py then?

Pan

**Comment by rbriden** [comment]
Hi Pan,

The repository is incomplete as of right now, and I'm too busy to fix it
unfortunately. However, you should be able to use model.py with the weights
from NYU pretty easily. Depending on what you're using this network for, I
recommend that you check out: https://github.com/iro-cp/FCRN-DepthPrediction.
This model is, since I last checked, the state-of-the-art model for depth
prediction. If you have anymore questions, feel free to contact me.

Best,
Ross
